server:
  port: 8080
  context-path: /account
spring:
  data:
    mongodb:
      host: ds133816.mlab.com
      port: 33816
      username: sngular
      password: s|ngular
      database: sngular 
   
eureka:
  instance:
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://eureka-server:8761/eureka 
